import { Hono } from 'hono'
import { handle } from 'hono/vercel'
import accounts from './accounts'
import categories from './categories'
import transactions from './transactions'
import summary from './summary'
import plaid from './plaid'

// Fix Axios request/responses
// Cannot use edge cause Plaid use Axios
export const runtime = 'nodejs'

const app = new Hono().basePath('/api')

// Routes must be chained to be generated by the RPC type.
// https://hono.dev/docs/guides/rpc#using-rpc-with-larger-applications
const routes = app
  .route("/accounts", accounts)
  .route("/categories", categories)
  .route("/plaid", plaid)
  .route("/summary", summary)
  .route("/transactions", transactions)

export const GET = handle(app)
export const POST = handle(app)
export const PATCH = handle(app)
export const DELETE = handle(app)

export type AppType = typeof routes